### ISSUE TITLE
Issue running demo package locally

### ISSUE THREAD

**Issue by dperrymorrow** [natemoo-re/micromorph#4]
Hey amazing repo... I think there is a great demand coming for tools like this that allow you to move away from SPA applications to more of a hybrid approach.

Im having trouble running the demo app locally

steps to reproduce:

`npm i` from root
`cd demo`
`npm i`

resulting error
```
➜  demo git:(main) ✗ npm i
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/../.npm/_logs/2022-03-28T17_17_11_106Z-debug.log
```

**Comment by natemoo-re** [comment]
Hey @dperrymorrow! I'm using [`pnpm`](https://pnpm.io/) to manage this repo, so running `pnpm i` from the root should work.

I still need to work on a better demo, the one included here isn't the most useful at the moment.

**Comment by natemoo-re** [comment]
Actually, I remembered that I do have a live demo you can check out!

The category tabs on https://astro.build/integrations/ are powered by `micromorph/spa` 👍🏻
